apiVersion: v1
kind: ServiceAccount
metadata:
  name: ev-scenario-replay
  namespace: fastapi
  annotations:
    # Created by the scenario-replay IRSA setup (ev-scenario-replay-role).
    eks.amazonaws.com/role-arn: arn:aws:iam::242254325514:role/ev-scenario-replay-role
