apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-eks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qp4534/EV-energy-management-gitops.git
    targetRevision: main
    path: apps/frontend-eks
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
