apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rul-diagnosis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qp4534/EV-energy-management-gitops.git
    targetRevision: main
    path: apps/rul-diagnosis
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
