apiVersion: v1
kind: Service
metadata:
  name: rul-diagnosis
  namespace: fastapi
spec:
  type: ClusterIP
  selector:
    app: rul-diagnosis
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
